/// <reference types="next/image-types/global" />

// Declares the module types for `import hero from "./hero.png"`.
//
// `next-env.d.ts` already references this, but that file is generated by
// `next build`/`next dev` and is gitignored, so it is absent on a clean
// checkout. `pnpm check-types` runs before any build in CI, which made
// static image imports fail there while passing locally. Keeping the
// reference in a checked-in file makes `tsc --noEmit` self-sufficient.
//
// To reproduce the original failure: delete `next-env.d.ts` and `.next`,
// then run `pnpm check-types`.
